spring:
    datasource:
        url: jdbc:mysql://localhost:3306/jalsani-server?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialization-mode: always

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        defer-datasource-initialization: true
mybatis:
    type-aliases-package: com.example.jalsaniserver
    config-locations:  classpath*:**/mybatis/mybatis-config.xml
    mapper-locations:  classpath*:**/mybatis/mapper/*.xml

logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

